"""change user id to uuid

Revision ID: ad52ddcbda9f
Revises: 8f6a78c65655
Create Date: 2026-03-16 10:25:09.750027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad52ddcbda9f'
down_revision: Union[str, Sequence[str], None] = '8f6a78c65655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop the old integer primary key and index, recreate as UUID
    op.execute('ALTER TABLE users DROP CONSTRAINT users_pkey')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_column('users', 'id')
    op.add_column('users', sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.create_primary_key('users_pkey', 'users', ['id'])
    op.create_index('ix_users_id', 'users', ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
