"""Add campaign table

Revision ID: f7a681aa6786
Revises: 6954171b44c5
Create Date: 2026-03-17 20:54:41.018924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7a681aa6786'
down_revision: Union[str, Sequence[str], None] = '6954171b44c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('lead_sources', sa.JSON(), nullable=True))
    op.add_column('campaign', sa.Column('lead_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'lead_limit')
    op.drop_column('campaign', 'lead_sources')
    # ### end Alembic commands ###
